### PR TITLE
[plugin.video.filmstarts] first small cosmetic corrections of the code

### PR DESCRIPTION
**Pull request by buhtz**
- Fixed the `<source>`-link in `addon.xml`.
- Pythonized the handling of variable `mode`. That means I removed the unneeded `if` statements.
The `global` variables are just a workaround in the current state. They will be removed in in the next steps.

**I didn't want to touch to much of the code in this first step.** In the next steps I refactoring the code in the way that there will be no need for global variables anymore. So this PR is just for *warming up*.

Found bug #23 while working on that.

Assign @tyl0re

### CODE REVIEW

**Comment by buhtz** [comment]
Please ignore _codacy-bot_'s comments. Your code is full of dirty formatings. ;) I will take that in account in the next PR.

**Comment by buhtz** [comment]
Dear @tyl0re can you plesae give a short message about the status of that PR?

**Comment by buhtz** [comment]
Status?

**Comment by buhtz** [comment]
Why do I get no reaction here? Contributions not welcome?

**Comment by tyl0re** [comment]
I Have written 2 Comments above, if you can change the global again to Parameter, because global Veriables should not be used. SO i can push it

**Comment by buhtz** [comment]
@tyl0re I don't see any comments from you - only from codacy-bot.

As I explained in the first comment. I will change the global-variables in the next step. Because I need to re-organize the complete code for this.

**Comment by buhtz** [comment]
As I tried to explain here: This PR was a first try to find out how to project managment works and how we fit together. I think the result is clear.

Contributors shouldn't treated like this. You haven't even responded to my questions, suggestions and critics!

**Comment by tyl0re** [comment]
Soory was in August in Holiday, and after that forgot it, since i made already an new Version, isnt compatible , i close it

**Comment by buhtz** [comment]
You wasted my time and my ressources. Thanks from my family!
Will never contribute to your code again. Not because you let me wait. It is because you are not able to communicate.

**Pull request closed without merging**
